---
extends: default
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
ignore: |
  vendor
rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments: disable
  comments-indentation:
    level: warning
  document-end: disable
  document-start: disable
  empty-lines:
    max-start: 1
    level: warning
  empty-values: disable
  hyphens: enable
  indentation:
    level: warning
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
    allowed-values: ['true', 'false', 'on']
