include Makefile

SERVER_SRC_FILE:=$(SERVER_DIR)/Containerfile.opensuse
SERVER_SOURCES:=$(SERVER_DIR)/smb.conf
SERVER_NAME:=samba-opensuse-container:$(TAG)
SERVER_REPO_NAME:=registry.opensuse.org/opensuse/samba-server:$(TAG)
BUILDFILE_SERVER:=.build.opensuse-server
