include Makefile

SERVER_SRC_FILE:=$(SERVER_DIR)/Containerfile.opensuse
AD_SERVER_SRC_FILE:=$(AD_SERVER_DIR)/Containerfile.opensuse
SERVER_SOURCES:=$(SERVER_DIR)/smb.conf
SERVER_NAME:=samba-opensuse-container:$(TAG)
AD_SERVER_NAME:=samba-ad-opensuse-container:$(TAG)
SERVER_REPO_NAME:=registry.opensuse.org/opensuse/samba-server:$(TAG)
AD_SERVER_REPO_NAME:=registry.opensuse.org/opensuse/samba-ad-server:$(TAG)
BUILDFILE_SERVER:=.build.opensuse-server
BUILDFILE_AD_SERVER:=.build.opensuse-ad-server
