include Makefile

OS_NAME:=opensuse
REPO_BASE:=registry.opensuse.org/opensuse/
SERVER_SRC_FILE:=$(SERVER_DIR)/Containerfile.opensuse
AD_SERVER_SRC_FILE:=$(AD_SERVER_DIR)/Containerfile.opensuse
CLIENT_SRC_FILE:=$(CLIENT_DIR)/Containerfile.opensuse
TOOLBOX_SRC_FILE:=$(TOOLBOX_DIR)/Containerfile.opensuse
SERVER_SOURCES:=$(SERVER_DIR)/smb.conf
