ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG INSTALL_PACKAGES_FROM=default
ARG SAMBA_VERSION_SUFFIX=""
ARG SAMBA_SPECIFICS=daemon_cli_debug_output,ctdb_leader_admin_command
ARG INSTALL_CUSTOM_REPO=

MAINTAINER John Mulligan <jmulligan@redhat.com>

# openSUSE Build Service specific build tags and labels:
#!BuildTag: opensuse/samba-server:latest
#!BuildTag: opensuse/samba-server:%%MINOR%%
#!BuildTag: opensuse/samba-server:%%PKG_VERSION%%
#!BuildTag: opensuse/samba-server:%%PKG_VERSION%%-%RELEASE%
# labelprefix=org.opensuse.samba-server
LABEL org.opencontainers.image.title="Samba container"
LABEL org.opencontainers.image.description="Samba container"
LABEL org.opencontainers.image.created="%BUILDTIME%"
LABEL org.opencontainers.image.version="%%PKG_VERSION%%-%RELEASE%"
LABEL org.opencontainers.image.vendor="SINK Project"
LABEL org.openbuildservice.disturl="%DISTURL%"
LABEL org.opensuse.reference="registry.opensuse.org/opensuse/samba-server:%%PKG_VERSION%%-%RELEASE%"
# endlabelprefix

COPY smb.conf /etc/samba/smb.conf
COPY install-packages.sh /usr/local/bin/install-packages.sh
RUN if [[ $(cat /etc/os-release) == *openSUSE* ]]; then \
    zypper --non-interactive install --no-recommends \
        findutils \
        python3-pip \
        python3-jsonschema \
        samba-python3 \
        python3-pyxattr \
        samba \
        samba-client \
        samba-winbind \
        tdb-tools \
        ctdb \
        glibc \
        sambacc; \
        zypper clean; \
else \
    /usr/local/bin/install-packages.sh \
        "${INSTALL_PACKAGES_FROM}" \
        "${SAMBA_VERSION_SUFFIX}" \
        "${INSTALL_CUSTOM_REPO}"; \
fi
RUN ln -sf /usr/share/sambacc/examples/minimal.json /etc/samba/container.json

VOLUME ["/share"]

EXPOSE 445

ENV SAMBACC_CONFIG="/etc/samba/container.json:/etc/samba/users.json"
ENV SAMBA_CONTAINER_ID="demo"
ENV SAMBA_SPECIFICS="$SAMBA_SPECIFICS"
ENTRYPOINT ["samba-container"]
CMD ["run", "smbd"]

# vim:set syntax=dockerfile:
