FROM registry.fedoraproject.org/fedora:34

ARG INSTALL_PACKAGES_FROM=default
ARG SAMBA_SPECIFICS=

COPY install-packages.sh /usr/local/bin/install-packages.sh
RUN /usr/local/bin/install-packages.sh "$INSTALL_PACKAGES_FROM"

COPY provision.sh /usr/local/bin/provision.sh
COPY run.sh /usr/local/bin/run.sh
COPY populate.sh /usr/local/bin/populate.sh

ENV POPULATE=/usr/local/bin/populate.sh
ENTRYPOINT ["/usr/local/bin/run.sh"]
