name: Nightly CI

on:
  schedule:
    - cron: '0 2 * * *'

jobs:

  build-nightly-server:
    runs-on: ubuntu-latest
    env:
      BUILDAH_FORMAT: oci
    steps:
    - uses: actions/checkout@v2
    - name: Build the nightly server image
      run: make build-nightly-server

  test-nightly-server:
    #needs: build-nightly-server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test the nightly server image
      run: make test-nightly-server

  push:

    # verify it passes build and test first
    needs: test-nightly-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: log in to quay.io
        run: podman login -u "${{ secrets.QUAY_USER }}" -p "${{ secrets.QUAY_PASS }}" quay.io
      - name: push nightly server image
        # note: forcing use of podman here, since we did podman login above
        run: make CONTAINER_CMD=podman push-nightly-server
