ARG BASE_IMAGE
FROM ${BASE_IMAGE}

MAINTAINER Shachar Sharon <ssharon@redhat.com>

# openSUSE Build Service specific build tags and labels:
#!BuildTag: opensuse/samba-toolbox:latest
#!BuildTag: opensuse/samba-toolbox:%%MINOR%%
#!BuildTag: opensuse/samba-toolbox:%%PKG_VERSION%%
#!BuildTag: opensuse/samba-toolbox:%%PKG_VERSION%%-%RELEASE%
# labelprefix=org.opensuse.samba-toolbox
LABEL org.opencontainers.image.title="Samba Toolbox container"
LABEL org.opencontainers.image.description="Samba Toolbox container"
LABEL org.opencontainers.image.created="%BUILDTIME%"
LABEL org.opencontainers.image.version="%%PKG_VERSION%%-%RELEASE%"
LABEL org.opencontainers.image.vendor="SINK Project"
LABEL org.openbuildservice.disturl="%DISTURL%"
LABEL org.opensuse.reference="registry.opensuse.org/opensuse/samba-toolbox:%%PKG_VERSION%%-%RELEASE%"
# endlabelprefix

RUN if [[ $(cat /etc/os-release) == *openSUSE* ]]; then \
    zypper --non-interactive install --no-recommends samba-client samba-test; \
else \
    dnf -y install samba-client samba-test; \
fi
